CREATE TABLE "FISHING_FLATFORM" (
	"F_NUM"	NUMBER(4)		NOT NULL,
	"PRICE"	NUMBER(6)		NULL
);

CREATE TABLE BOOKING (
	B_CODE CHAR(5) NOT NULL,
	DAYS NUMBER(2) NULL,
	F_NUM NUMBER(4) NOT NULL
);

ALTER TABLE "FISHING_FLATFORM" ADD CONSTRAINT "PK_FISHING_FLATFORM" PRIMARY KEY (
	"F_NUM"
);

ALTER TABLE "BOOKING" ADD CONSTRAINT "PK_BOOKING" PRIMARY KEY (
	"B_CODE"
);

-- FISHING_FLATFORM 테이블에 데이터 삽입
INSERT INTO "FISHING_FLATFORM" ("F_NUM", "PRICE") VALUES (1001, 15000);
INSERT INTO "FISHING_FLATFORM" ("F_NUM", "PRICE") VALUES (1002, 20000);
INSERT INTO "FISHING_FLATFORM" ("F_NUM", "PRICE") VALUES (1003, 25000);
INSERT INTO "FISHING_FLATFORM" ("F_NUM", "PRICE") VALUES (1004, 18000);
INSERT INTO "FISHING_FLATFORM" ("F_NUM", "PRICE") VALUES (1005, 22000);

-- BOOKING 테이블에 데이터 삽입
INSERT INTO "BOOKING" ("B_CODE", "DAYS", "F_NUM") VALUES ('B001', 2, 1001);
INSERT INTO "BOOKING" ("B_CODE", "DAYS", "F_NUM") VALUES ('B002', 3, 1002);
INSERT INTO "BOOKING" ("B_CODE", "DAYS", "F_NUM") VALUES ('B003', 1, 1003);
INSERT INTO "BOOKING" ("B_CODE", "DAYS", "F_NUM") VALUES ('B004', 4, 1004);
INSERT INTO "BOOKING" ("B_CODE", "DAYS", "F_NUM") VALUES ('B005', 2, 1005);
INSERT INTO "BOOKING" ("B_CODE", "DAYS", "F_NUM") VALUES ('B006', 1, 1001);
INSERT INTO "BOOKING" ("B_CODE", "DAYS", "F_NUM") VALUES ('B007', 3, 1003);
INSERT INTO "BOOKING" ("B_CODE", "DAYS", "F_NUM") VALUES ('B008', 2, 1004);

-- 데이터 확인
SELECT * FROM "FISHING_FLATFORM";
SELECT * FROM "BOOKING";
